services:
  dev_hack-foro-devcontainer:
    image: node:lts
    container_name: hack-foro_devcontainer
    environment:
      - IsLocalSide=true
    volumes:
      - ../:/workspace:rw
    command: sleep infinity



