services:
  dev_hack-foro-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hack-foro_devcontainer
    environment:
      - IsLocalSide=true
    networks:
      - backend_devcontainer
    volumes:
      - ../:/workspace:rw
    command: sleep infinity


networks:
  backend_devcontainer:
    driver: bridge
    name: backend_devcontainer
